<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="dev-Inspiron-3521" name="First Test" tests="5" failures="2" timestamp="15 Sep 2015 04:31:44 GMT" time="0.07" errors="0">
  <testcase name="testApp" time="0.016" classname="org.shiftleft.test.selenium.AppTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at org.shiftleft.test.selenium.AppTest.testApp(AppTest.java:20)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testApp -->
  <testcase name="just_first_test" time="0.001" classname="org.shiftleft.test.selenium.DemoTesting">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
	at org.shiftleft.test.selenium.DemoTesting.just_first_test(DemoTesting.java:62)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- just_first_test -->
  <testcase name="login_message_in_wrong_password_test" time="0.001" classname="org.shiftleft.test.selenium.DemoTesting"/>
  <testcase name="login_message_in_wrong_username_test" time="0.001" classname="org.shiftleft.test.selenium.DemoTesting"/>
  <testcase name="login_validation_test" time="0.001" classname="org.shiftleft.test.selenium.DemoTesting"/>
</testsuite> <!-- First Test -->
